# Versione MongoDB dell'immagine ozonapp.db. Override:
#   MONGO_VERSION=8.2.12 ./build_imges.sh
#
# MongoDB 8.3.8 e il tag mobile 8.0 non partono sul kernel 7.0.12-linuxkit
# di Docker Desktop. La 8.2.12 e' verificata su quel kernel: tenere la patch
# version fissata, senza usare un tag mobile.
ARG MONGO_VERSION=8.2.12
FROM mongo:${MONGO_VERSION}
ARG TZ
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
