all:
  children:
    ozonapp:
      hosts:
        dev-target:
          ansible_host: dev-host-not-set.invalid
          ansible_user: deploy
          ansible_port: 22
          ansible_become: false
