---
- name: Deploy ozon-env-app stack
  hosts: ozonapp
  gather_facts: false
  vars:
    ozonapp_action: deploy
    ozonapp_repo_root: "{{ playbook_dir | dirname | dirname }}"
  roles:
    - role: ozonapp_deploy
